### ISSUE TITLE
S3不兼容本地部署minio

### ISSUE THREAD

**Issue by Henvy-Mango** [Yuri-NagaSaki/ImageFlow#27]
```yml
services:
  images:
    image: soyorins/imageflow
    ports:
      - 8686:8686
    environment:
      # API Configuration
      - API_KEY=${API_KEY:-default_api_key}

      # Storage Configuration
      - STORAGE_TYPE=${STORAGE_TYPE:-local}
      - LOCAL_STORAGE_PATH=/app/static/images

      # S3 Configuration
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - CUSTOM_DOMAIN=${CUSTOM_DOMAIN:-}

      # Image Processing Configuration
      - MAX_UPLOAD_COUNT=${MAX_UPLOAD_COUNT:-20}
      - IMAGE_QUALITY=${IMAGE_QUALITY:-80}
      - WORKER_THREADS=${WORKER_THREADS:-4}
      - COMPRESSION_EFFORT=${COMPRESSION_EFFORT:-6}
      - FORCE_LOSSLESS=${FORCE_LOSSLESS:-false}
    volumes:
      - ./static/images:/app/static/images
      - ./config:/app/config
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8686/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001" 
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_LOG_QUERY_URL=on
      - MINIO_ROOT_PASSWORD=12345678
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

```log
images-1  | 2025/04/11 03:04:18 Initializing S3 client with endpoint: http://minio:9000
images-1  | 2025/04/11 03:04:18 S3 client initialized successfully for bucket: test
images-1  | 2025/04/11 03:04:18 Initializing S3 client with endpoint: http://minio:9000
images-1  | 2025/04/11 03:04:18 S3 client initialized successfully for bucket: test
images-1  | 2025/04/11 03:04:18 S3 metadata store initialized
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/original/landscape
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/original/portrait
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/landscape/webp
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/landscape/avif
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/portrait/webp
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/portrait/avif
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/gif
images-1  | 2025/04/11 03:04:18 Created directory: /app/static/images/metadata
images-1  | 2025/04/11 03:04:18 Starting image cleaner with interval: 1m0s
images-1  | 2025/04/11 03:04:18 Image cleaner started
images-1  | 2025/04/11 03:04:18 Starting server on 0.0.0.0:8686 with s3 storage
minio-1   | MinIO Object Storage Server
minio-1   | Copyright: 2015-2025 MinIO, Inc.
minio-1   | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
minio-1   | Version: RELEASE.2025-04-08T15-41-24Z (go1.24.2 linux/amd64)
minio-1   | 
minio-1   | API: http://172.21.0.3:9000  http://127.0.0.1:9000 
minio-1   | WebUI: http://172.21.0.3:9001 http://127.0.0.1:9001  
minio-1   | 
minio-1   | Docs: https://docs.min.io
images-1  | 2025/04/11 03:04:25 Error listing metadata objects from S3: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://test.minio:9000/?list-type=2&prefix=metadata%2F": EOF
images-1  | 2025/04/11 03:04:25 Error listing expired images: failed to list metadata objects from S3: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://test.minio:9000/?list-type=2&prefix=metadata%2F": EOF
images-1  | 2025/04/11 03:05:24 Error retrieving tags: failed to list objects from S3: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://test.minio:9000/?list-type=2&prefix=metadata%2F": EOF
images-1  | 2025/04/11 03:05:24 Error listing images: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://test.minio:9000/?list-type=2&prefix=original%2Flandscape%2F": EOF
images-1  | 2025/04/11 03:05:32 Error listing metadata objects from S3: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://test.minio:9000/?list-type=2&prefix=metadata%2F": EOF
images-1  | 2025/04/11 03:05:32 Error listing expired images: failed to list metadata objects from S3: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://test.minio:9000/?list-type=2&prefix=metadata%2F": EOF
images-1  | 2025/04/11 03:05:37 Error listing images: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://test.minio:9000/?list-type=2&prefix=original%2Flandscape%2F": EOF
```
